### ISSUE TITLE
Crash running make_real_readme.py

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#1]
I ran it within PyCharm.  Best I can tell, it's a command line program, but can't tell for sure.  Your readme indicates that it is:
`python3 make_real_readme.py`

Here is the crash.

```
C:\Python\Anaconda3\python.exe C:/Python/PycharmProjects/GitHub/PySimpleGUIDocGen/make_real_readme.py
Traceback (most recent call last):
  File "C:/Python/PycharmProjects/GitHub/PySimpleGUIDocGen/make_real_readme.py", line 195, in <module>
    with open('<<FINAL readme.md', 'w', encoding='utf-8') as ff:
OSError: [Errno 22] Invalid argument: '<<FINAL readme.md'
```

I will add a GUI to this program once we get it all nailed down.  I would like the entire process to be a "Double Click" type of experience with a GUI showing progress and errors.   I should be able to easily add this I'm pretty sure.

**Comment by nngogol** [comment]
Now it's working.
