### ISSUE TITLE
GUI: I removed it. LEARN SHELL. - I'm the customer, fix your fucking software

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#10]
I'm super frustrated by the make_real_readme.py file.

Maybe I'm an idiot when it comes to these billions of decorators, maybe I can't find the `exit()` that must be called somewhere, or maybe the software is broken.   All I know is the same result keeps happening.

I tried adding my own "Print" after the `cli()` call, but it never gets to the code.  It bombs out with exit code 0 but it isn't doing it after the return, that's for sure.

I'm also unable to run this file with a debugger.

Does it HAVE to be this fucked up and complex so that I can't run it in a debugger or I can't add a GUI?  I don't understand the need for the decorators and stuff. If it's for my benefit, I don't seem to be getting any from it as the same thing kept happening, errors with no output.

Then I finally checked the log file and found you had duplicate entries for Output Element's Methods.

Can I ask that we stick with 1 launching method?  Previously it was with the usage.py file.  Now that file disappeared and it seems like I'm supposed to run make_real_readme.py directly.

I tried the example from the readme of `python make_real_readme.py --help` and it dumped:
```
C:\Python\PycharmProjects\GitHub\PySimpleGUIDocGen - nngogol\db>python make_real_readme.py --help
Traceback (most recent call last):
  File "C:\Python\Anaconda3\lib\site-packages\click\_compat.py", line 105, in __getattr__
    return getattr(self._stream, name)
AttributeError: 'TKOutput' object has no attribute 'closed'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "make_real_readme.py", line 444, in <module>
    cli()
  File "C:\Python\Anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python\Anaconda3\lib\site-packages\click\core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "C:\Python\Anaconda3\lib\site-packages\click\core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "C:\Python\Anaconda3\lib\site-packages\click\core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "C:\Python\Anaconda3\lib\site-packages\click\core.py", line 1477, in handle_parse_result
    self.callback, ctx, self, value)
  File "C:\Python\Anaconda3\lib\site-packages\click\core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "C:\Python\Anaconda3\lib\site-packages\click\core.py", line 860, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "C:\Python\Anaconda3\lib\site-packages\click\utils.py", line 260, in echo
    file.write(message)
SystemError: <built-in method replace of str object at 0x0000019BADC4B750> returned a result with an error set

C:\Python\PycharmProjects\GitHub\PySimpleGUIDocGen - nngogol\db>
```

I know we're still working on it, but we're going 1 forward, 2 back

**Comment by MikeTheWatchGuy** [comment]
OK, but seriously.....

## The GUI

I WILL DO ANY GUI there is to do.  OK?  Don't worry about a GUI at all.

**BUT** I need interfaces that I can use with a GUI.  If it has to be a command line app, that's fine.  Just make sure I can call it from Python and that I can re-route stdout to my window.  

This is what I do with the Make-EXE.  There are a TON of warnings and other messages that spit out of PyInstaller.  It's unusual in that it will scroll and output data to the window in realtime as the command line application is spitting it out.  It's a specific technique and I have the design pattern.  I'm sure it's in the Demo Programs.  I'm doing it anyway so don't worry about it.

**Comment by nngogol** [comment]
No. It's really simple.
`click` - is a framework for CLI apps.
`make_real_readme.py` - module for generating docs.
`usage.py` - an example (just move it do to `db/` folder)

1) You can call this CLI app using `subprocess,Pooen` and pass arguments. It's simple.
2) if you want, you can directly `import make_real_readme` in you GUI software and mann args for `main(...)` function

**Comment by MikeTheWatchGuy** [comment]
I think the best option, in the long run, will be to import make_real_readme.

This will enable a "tight" GUI. One that has a lot more visibility into what's going on.

ALSO, this enables you to release this code on PyPI!  The `make_real_readme` package!  OK, so maybe we need a new marketing name :-)

I don't think anything like this exists.   I don't recall anything that you can place tags into a .md file and then the code will go grab doc strings from another piece of code and will drop in the doc strings in the right places.  You may have invented the next HUGE big thing on GitHub!

**Comment by nngogol** [comment]
I think, that's narrow task, so I will not borrow with it.
