### ISSUE TITLE
Try this handy way of getting info about a class

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#11]
You may be able to use this as it really does a great job of creating sorted views of a class.
```python
print(sg.ObjToStringSingleObj(sg.Window))
```

That will print a "single Object" of any kind.  I just did window in this example.  It can be a variable of course too.

**Comment by nngogol** [comment]
Closing this issue, because there is `get_CF_insight.py` file
