### ISSUE TITLE
Please bump version number to 4.1.0.2 Unreleased

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#12]
I like your code well enough that it's the NEW MASTER on GitHub.

Rather than do a pull request on your stuff, just change that one line of code (line 2) at the top of the file.

BTW, I may not be following the right / best practice on how I'm doing the string.  I've not seen any other package define both a __version__  and `version`.  I did it because a program can't access `sg.__version__` but it can access `sg.version`.  This enables me to instruct someone with the debugger to simply look at the variable sg.version in the built-in debugger.

Nice work on the doc strings!

We will have to remove that triangle character unfortunately.  Let's talk about that key parameter thing.  It's not something I really want to track.

**Comment by nngogol** [comment]
I will take your PSGlib.py and it will be replaced.
