### ISSUE TITLE
Remove special characters from PySimpleGUIlib.py

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#13]
We can't use any special characters in the base PySimpleGUI.py file.  We can in other ports but not the tkinter one.  The reason is that Python 2.7 crashes when reading these special characters, even when in a comment.

**Comment by nngogol** [comment]
What kind of special chars do you mean? These: ▲▒?

**Comment by nngogol** [comment]
Done.
