### ISSUE TITLE
:return: is currently at top of the comment blocks.  Used to be at the bottom (the standard location?)

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#16]
Here's the Popup definition.  I noticed others that have return values also have them moved to the top.
When PyCharm creates doc strings, they put the Return value at the end.  I think it's the standard location.

I can easily fix these as I'm going through the PySimpleGUI.py file and adding documentation (TODAY!)

Currently in the code:
```python
def Popup(*args, title=None, button_color=None, background_color=None, text_color=None, button_type=POPUP_BUTTONS_OK,
          auto_close=False, auto_close_duration=None, custom_text=(None, None), non_blocking=False,
          icon=DEFAULT_WINDOW_ICON, line_width=None,
          font=None, no_titlebar=False, grab_anywhere=False, keep_on_top=False, location=(None, None)):
    """Popup - Display a popup box with as many parms as you wish to include
    :return:

    :param *args: 
    :param title:  
    :param button_color: button color (foreground, background)
    :param background_color: color of background 
    :param text_color: color of the text 
    :param button_type:  (Default value = POPUP_BUTTONS_OK)
    :param auto_close:  (Default = False)
    :param auto_close_duration:  
    :param custom_text:  
    :param non_blocking:  (Default = False)
    :param icon: Icon to display (Default value = DEFAULT_WINDOW_ICON)
    :param line_width: Width of lines in characters 
    :param font: ▲ specifies the font family, size, etc 
    :param no_titlebar:  (Default = False)
    :param grab_anywhere: If True can grab anywhere to move the window (Default = False)
    :param location: Location on screen to display 
    :param location:  (Default = (None))

    """
    if not args:
        args_to_print = ['']
```

**Comment by nngogol** [comment]
ALWAYS put `:return:` guy at EOD (it's like EOF, but End Of Doc).
`:return:` guy will be oneliner in 95% cases, but, if it's and the end of __doc__ - you can make it multiline (you wouldn't).

**Comment by MikeTheWatchGuy** [comment]
Do all funcs/methods have to have a `:return`:?
Does there have to be a blank line?
I've been deleting the blank lines, so if some are mandatory, please let me know.

**Comment by nngogol** [comment]
`:return:` is optional.
from all the functions in PSG - there is a lot of popups,, that have identical `__doc__`.
If we talk about methods - they can be useful, because `Get()` can mean different things in different widgets.

**Comment by MikeTheWatchGuy** [comment]
Do I need any of the blank lines?
