### ISSUE TITLE
Need to move `Usage.py` over to db folder for it to run?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#19]
In order for me to "double-click" the `usage.py` file I have to move it over to the `db` folder first.  Otherwise it doesn't find the `make_read_readme` to `import`.   

I like the popup!!

Oh, and I like the log too because I found the duplicated tag error in there.

Hmmm.... that means I can only show the definition of a method in only one place.

**Comment by MikeTheWatchGuy** [comment]
Here are the windows that are involved with me making one of these.  I double click on usage.py and the black window is the output terminal that I can see because of the popup.

![image](https://user-images.githubusercontent.com/13696193/60386133-4ca58f80-9a5f-11e9-8745-0b32f4184d5a.png)

**Comment by nngogol** [comment]
done
