### ISSUE TITLE
[Bug / Enhancement] Name of method not appearing

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#20]
For the InputText Element, the Methods don't look quite right.

The enhancement part - it would be nice to have the line with the name of the method and the text description of it to be bold.  I think this will make finding them easy.  Right now locating the Get method is difficult because there is no signature for the Get function listed like there is for the Update method.  

What did I do wrong in the readme or the code?

The text that describes the Update method isn't shown like the Get() one is.
![image](https://user-images.githubusercontent.com/13696193/60386501-7791e280-9a63-11e9-96fc-e3e6b7588232.png)

This is what is inside the 2_readme:
![image](https://user-images.githubusercontent.com/13696193/60386523-d8b9b600-9a63-11e9-954c-bb022a764488.png)

**Comment by MikeTheWatchGuy** [comment]
Oh, this idea just came to mind.  I could add my own heading before each method:

#### Update


#### Get


#### SetFocus


I'll try this to see if it helps.

**Comment by nngogol** [comment]
I fix it. PLEASE, don't add `heading before each method:`

**Comment by MikeTheWatchGuy** [comment]
I tried it and it didn't look bad.  It's the only way to get them listed in a table of contents.  They have to be headings.

The Get method still isn't showing up with it's signature.  It doesn't show the call definition and parameters.  I've looked at my code several times and it looks right to me.  I'll check it all into my forked GitHub so you can see the .py file if you want.

Here's how it turned out.

![image](https://user-images.githubusercontent.com/13696193/60387190-84b3cf00-9a6d-11e9-9f6a-bc3276c7dfce.png)

**Comment by MikeTheWatchGuy** [comment]
I think I **like** doing it this way.... except for the `Get` and `SetFocus` not doing quite the right thing above.

The reason I like not having you do the heading is that it allows me to insert these tags in multiple places and for multiple uses beyond this one document.  If the heading were placed in your generated code, then there are times that I would likely have to go hand edit and remove them.
```
### Methods

#### Update

<!-- <+InputText.Update+> -->

#### Get

<!-- <+InputText.Get+> -->

#### SetFocus

<!-- <+InputText.SetFocus+> -->
```

If this is the entire Methods section for an element, then I LIKE IT!

There's nothing there... a few lines of text, and I get all that awesome .md stuff :-)


-------------------------------

## The problems above

I do see a few problems in the above stuff.  Two things.
1. The Get function isn't showing the signature of the function (like you see working with SetFocus)
2. SetFocus isn't getting the text from the .py file and showing it.  Maybe I'm confused?

Here is the code from PySimpleGUIlib.py:

```python
    def Get(self):
        """
        Read and return the current value of the input element. Must call `Window.Read` or `Window.Finalize` prior

        :return: (str) current value of Input field or '' if error encountered
        """
        try:
            text = self.TKStringVar.get()
        except:
            text = ''
        return text

    def SetFocus(self, force=False):
        """
        Sets focus to this element using focus_set. Will use focus_force if force flag set. Must call `Window.Read` or `Window.Finalize` prior

        :param force: (bool) if True then tkinter's `Entry.focus_force` will be called instead of `Entry.focus_set`
        """
        try:
            if force:
                self.TKEntry.focus_force()
            else:
                self.TKEntry.focus_set()
        except:
            pass
```

**Comment by nngogol** [comment]
I fix it.

**Comment by MikeTheWatchGuy** [comment]
It would be helpful to see a screenshot or something to show how it was fixed.

**Comment by MikeTheWatchGuy** [comment]
Can we re-open this as it's still happening?  We can link the new one I just entered if that's better.
