### ISSUE TITLE
Why restriction on repeating a tag?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#21]
I noticed with the checked in version of 2_readme that it will not build.  It produces an error about the Output element having a tag that was in the document twice.

Why is that flagged as an error?

Does this mean I cannot re-use **any** tags that I used earlier in the document?

Why do I ask?  Because I want to be able to include a "Summary" sheet that only lists the signatures for each of the Element's init calls and nothing else.  This will give some people everything they need to write PySimpleGUI code without an IDE.

**Comment by nngogol** [comment]
fixed/
