### ISSUE TITLE
[URGENT - Broken] Missing methods with latest code

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#24]
I completely overwrote my code with your latest.  Then I changed the PySimpleGUIlib.py file, ran the usage.py and got my readme.md

I don't know if it's the PySimpleGUIlib.py file I supplied or something else, but the 3 methods are only coming through as 1.

I'll turn on logs, etc, but wanted to send this to you right away in case it's easy.

![image](https://user-images.githubusercontent.com/13696193/60399175-bb055300-9b2e-11e9-9dfc-f41160e3f6e9.png)

This is all I got in the readme for all of the InputText element.

![image](https://user-images.githubusercontent.com/13696193/60399188-dbcda880-9b2e-11e9-8593-98eba02daa15.png)

I'm sure I'm doing something wrong.

I checked in all my code including the PySimpleGUIlib.py file into my DocGen GitHub for you to see.

Sorry I'm such a moron when it comes to formatting these things correctly.

**Comment by nngogol** [comment]
Yes, it's my bad "merge work". Already fixed.

**Comment by MikeTheWatchGuy** [comment]
See what I mean about those merges?  They're a bitch and it's easy to make a mistake.  Hate them.
