### ISSUE TITLE
[Enhancement] Remove description from Signature Tag.........

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#28]
Right now we're getting text before the signature:

![image](https://user-images.githubusercontent.com/13696193/60402917-fc642580-9b63-11e9-828a-8a23010fc36d.png)

Would like to exclude all text up to the function signature.

**Comment by MikeTheWatchGuy** [comment]
![image](https://user-images.githubusercontent.com/13696193/60402950-ae9bed00-9b64-11e9-890e-922b14d0c289.png)

**Comment by nngogol** [comment]
Fixed/
