### ISSUE TITLE
[Question] SDK Quick Reference

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#30]
Recall the SDK Quick Reference Demo Program?  It was pretty great, when it was kept up to date.

Here's what it looks like:
![image](https://user-images.githubusercontent.com/13696193/60441320-bef3ac80-9be4-11e9-9e88-df7697070d14.png)

And the methods tab:
![image](https://user-images.githubusercontent.com/13696193/60441341-c915ab00-9be4-11e9-9fd0-915dac9750ad.png)

Then it hit me, this is the same data that you're producing from the .py file.

**This is NOT part of this project.....**

Could your code be given an interface that will return lists of functions, methods, classes and provide the ability to get the docstring returned as a `string` object?  Then I could rewrite this SDK quick reference and it'll be 100% up to date because it can use the PySimpleGUI that's being imported by the program 👍 

Let's talk later about hiring you for another job to get this kind of interface.

**Comment by nngogol** [comment]
It's cool idea. Okay.

**Comment by MikeTheWatchGuy** [comment]
I love the interface you proposed today. I never thought about having DIRECT access to this kind of information.  I only thought about maybe using regex to get it from a text file.  Your structure is going to make this a wonderful tool, capable of documenting the VERY SPECIFIC version of PySimpleGUI they are running.   

Wow, that's such a rare thing if you think about it.  How many packages have a "quick reference" program that you can run, copy and paste from?  How many packages have ANY documentation on their SDK?

You're making this project look really good and very **sophisticated and professional**.  People loved the documentation before, this is like `documentation ** 2`.  Or is it `documentation ^ 2` in Python?
