### ISSUE TITLE
Why I have to do # Method_name

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#34]
Wanted to show you a graphic example of why I must have a # Method_name before the methods.

Here's the InputText Element's Method area:
![image](https://user-images.githubusercontent.com/13696193/60548995-88578800-9cf1-11e9-98c4-81a68f0e0f18.png)

Question, what does the first line of text mean?
## Methods
Changes some of the settings for the Input Element. Must call Window.Read or Window.Finalize prior

It is the description for the Update Method.  So, BEFORE that line of text, I need something that announces this as the `Update` method.  My "fix" was to add a ## Update before adding your tags.  Or maybe I can write something that will do some of this for me in the "Create All Tags" program I just checked in.  Maybe it can also create the headers too?

**Comment by nngogol** [comment]
Yeah, me too, Mike. I was immediately diffused, coz I couldn't orient properly in the text.
Fixed.
