### ISSUE TITLE
[Bug?] How can I get a parameter table when there is only a return value?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#36]
At the moment, when I have a func/method with no parameters but have a return value, I do not get the table containing the return value.

`Window.CurrentLocation` is a good example:

I see this in the readme:
![image](https://user-images.githubusercontent.com/13696193/61006879-68e7dd00-a339-11e9-927c-1b33db575c64.png)

And this is the code that matches:
![image](https://user-images.githubusercontent.com/13696193/61006932-8e74e680-a339-11e9-8572-944e1bd08456.png)

**Comment by nngogol** [comment]
fixed
