### ISSUE TITLE
[Bug] Newline in return definition causes the info to be shown in left hand column

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#37]
This is from the `Window.Read` definition:
![image](https://user-images.githubusercontent.com/13696193/61007050-d5fb7280-a339-11e9-9e8a-4683978b813c.png)

Notice the **Return** portion.

![image](https://user-images.githubusercontent.com/13696193/61007093-ef9cba00-a339-11e9-8c44-dcac65038efc.png)

Is it possible to locate the text in the right hand column?

**Comment by nngogol** [comment]
fixed
