### ISSUE TITLE
[Bug] A method without any parameter and any return values is not displayed correctly

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#38]
![image](https://user-images.githubusercontent.com/13696193/61008737-676ce380-a33e-11e9-9c07-1fea0a2fe074.png)

Both the Maximize and Minimize methods have no parms and no return values.  Both of them have the Text shown in the gray area.  The text should be outside the gray area, above it like the other method calls like this:

![image](https://user-images.githubusercontent.com/13696193/61008780-8bc8c000-a33e-11e9-8ebb-30d1214e06be.png)

**Comment by nngogol** [comment]
fixed in latest version

**Comment by MikeTheWatchGuy** [comment]
![image](https://user-images.githubusercontent.com/13696193/61093897-a2444980-a41a-11e9-8359-c6e414fcbe8d.png)

I see that Move has its parameters on a single line now.  Is that a special case you made now?  I don't see any of the methods being presented in the same way as classes and functions.

**Comment by MikeTheWatchGuy** [comment]
Nice job fixing this one
