### ISSUE TITLE
[Bug] Titles are being added before SOME method calls

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#39]
It's my responsibility to add the headers, right?

But it looks like sometimes you do too.

Here's Fill for example from the final readme:

![image](https://user-images.githubusercontent.com/13696193/61093672-a328ab80-a419-11e9-86b0-739165d57314.png)

My source doesn't have 2 of them.

I guess I'll have to hand edit if I want to post this tonight.  I'm getting really close to finishing section 1.  I'm not even really into section 2 yet.

Here is what my section 2 has:

![image](https://user-images.githubusercontent.com/13696193/61093716-e125cf80-a419-11e9-82b1-8abdfb6f3973.png)

**Comment by nngogol** [comment]
I added option in `usage.py` file, **BUT** I think, you should 99% delete hand-written section-heading, because it's useless .

**Comment by MikeTheWatchGuy** [comment]
I don't understand what you mean to delete.

Do you mean delete the entire section 2 of the document?
