### ISSUE TITLE
General Purpose Release for everyone?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#4]
Have you thought about releasing your stuff as a package?

I can totally see developers that are struggling, like me, to get documentation working.  The only other project I've seen get this right is Remi.  They are generating the docs from the code.  I think Kivy is to.

Don't worry about adding the GUI to this. I'll do it using PySimpleGUI which will enable it to be run anywhere, including the web. And it DOES make logical sense that the PySimpleGUI documentation generator be written in PySimpleGUI.  I know you're slower in PySimpleGUI so I'll do it.  I'll steal your design 👍

**Comment by nngogol** [comment]
Sound good to me!
It would be easier for py beginners to make docs.

**Comment by nngogol** [comment]
I changed my mind. I think, that DocGen - is specific software. It's easier to use Sphinx. Really.
