### ISSUE TITLE
[Bug] Something weird with Layout

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#40]
![image](https://user-images.githubusercontent.com/13696193/61094177-ef74eb00-a41b-11e9-8ced-831bd47b59e4.png)

Here are the comments in the source

![image](https://user-images.githubusercontent.com/13696193/61094213-2e0aa580-a41c-11e9-844b-aa1377a100ee.png)

**Comment by nngogol** [comment]
fixed in last version by adding params. Look at `usage.py` file.
