### ISSUE TITLE
[Bug] HTML Code Visible in final Readme

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#41]
We're getting VERY CLOSE!

Check out this html that started to show up at this point in the file.
![image](https://user-images.githubusercontent.com/13696193/61155265-77abcc80-a4be-11e9-9ad9-a7ec7d62f04b.png)

And it continues to popup throughout the document after that point:
![image](https://user-images.githubusercontent.com/13696193/61155297-8befc980-a4be-11e9-8213-7d95672be612.png)

**Comment by MikeTheWatchGuy** [comment]
This is only happening in the Visual Studio version.  

I do like this tool, but damn, that's a nasty bug they've got!

Maybe nothing for you to do but close this??

**Comment by nngogol** [comment]
It would be cool to have offline html and pdf output of md, instead of relying on some `extension-plugin` package for `text-editor`.
