### ISSUE TITLE
** HELP!!!  __init__ is no longer being added to the readme!

### ISSUE THREAD

**Issue by PySimpleGUI** [nngogol/PySimpleGUIDocGen#49]
Damn, I didn't test the latest releases very well and just uploaded the documentation without really looking at it.

The docs at http://www.PySimpleGUI.org no longer show ANY definitions of the actual initialization, the most important part of the docs!  DOH!

Here's how it looks now:
![image](https://user-images.githubusercontent.com/46163555/64209840-a2d3ec00-ce6f-11e9-9af8-d474ea5caad1.png)

I had to roll back to the July 20 version in order to get them again:

![image](https://user-images.githubusercontent.com/46163555/64209985-fe9e7500-ce6f-11e9-9356-f78e38d365ab.png)

**Comment by nngogol** [comment]
fixed
