### ISSUE TITLE
[ Enhancement ] Create a "CallSignature.md" file from section in 2_readme.md

### ISSUE THREAD

**Issue by PySimpleGUI** [nngogol/PySimpleGUIDocGen#53]
Enhancement request....

At the moment, one huge readme.md file is created.  In the past, this has worked very well.

Users are beginning to complain that it takes too long to load.  

One solution, this one, is to take the code beginning on line 3206 of 02_readme.md
```
# ELEMENT AND FUNCTION CALL REFERENCE
```

going all the way to the end of that file, and move it to another file named 5_CallSignature.md.

When making the readme, the creator program will not only glue together the current 4 parts still, but it also process this new 5_CallSignature.md file and instead of combing with the others, write a new file named CallSignature.md.

This will allow me to put this file into the folder named docs on the PySimpleGUI github.  The readthedocs website processes this GitHub folder and makes a new tab at the top of this page for every .md file it finds:

http://www.PySimpleGUI.org

I suppose at the top of the new readme we should add a link that will pull up this new tab.  We should be able to use the same kind of link to get to the cookbook (http://Cookbook.PySimpleGUI.org) that will lead them over to the call signature / call reference section.

**Comment by nngogol** [comment]
Fixed
