### ISSUE TITLE
Remove warning about missing returns in docstring

### ISSUE THREAD

**Issue by PySimpleGUI** [nngogol/PySimpleGUIDocGen#56]
There is a warning that is being shown that should no longer be shown because it's not an error

I commented out this line of code in make_real_readme.py and it works great!

![image](https://user-images.githubusercontent.com/46163555/85946190-934af580-b910-11ea-80f1-e9204b5c0432.png)

It's much better to have the table in the final .md file not show the word "RETURN" if there are no return values and to show a row with RETURN and nothing else.

I think it's all working great except for that warning being displayed.

**Comment by nngogol** [comment]
Ok, fixed.
