### ISSUE TITLE
BUG - getting warnings about empty table when one is supplied

### ISSUE THREAD

**Issue by PySimpleGUI** [nngogol/PySimpleGUIDocGen#57]

**Comment by PySimpleGUI** [comment]
![image](https://user-images.githubusercontent.com/46163555/85946240-07859900-b911-11ea-8099-1ba6129a5518.png)

The definition looks like this:

```python

def EasyPrintClose():
    """
    Close a previously opened EasyPrint window
    :return:
    :rtype:
    """
    if _DebugWin.debug_window is not None:
        _DebugWin.debug_window.Close()
        _DebugWin.debug_window = None

```

I've tried removing the return too and I get the same error.


The output in the call_reference.md file looks OK because it still shows the description and the call:

![image](https://user-images.githubusercontent.com/46163555/85946294-6b0fc680-b911-11ea-8874-ca897ac390ff.png)


I think this is a case where it's a false warning and can be removed.

The question - are there situations where a warning is still needed that removing this warning will cause us to miss?

**Comment by nngogol** [comment]
fixed
