### ISSUE TITLE
Can we stop using PySimpleGUIlib.py?

### ISSUE THREAD

**Issue by PySimpleGUI** [nngogol/PySimpleGUIDocGen#60]
I would like to not have to copy PySimpleGUI.py from my development location into a file PySimpleGUIlib.py to get the readme created.

It would be nice is the SAME PySimpleGUI.py file used to run the GUI were used as the input.

I'm going to experiment to see if I can remove it.

**Comment by nngogol** [comment]
when I do `import PySimpleGUI as sg`
python searched 1) current folder 2) (*if it fails in prev step*) find in `/site-packages` folder

Your `development location` is something like `.../site-packages/PySimpleGUI/PySimpleGUI.py`?
If it is - then ok, I'm throwing away PSGlib.py

**Comment by nngogol** [comment]
fixed
