### ISSUE TITLE
Please change these 2 warnings....

### ISSUE THREAD

**Issue by PySimpleGUI** [nngogol/PySimpleGUIDocGen#64]
Can we not use "BOY"?  I feel like a slave being told what to do.

I've changed my version to show  "Warning"

I also dropped the "Hi Mike" portion.  Just the warning is good.

It's a professional piece of software now!  Those things were fun, but now that it's a real thing it's better to be a more polished product.

**Comment by PySimpleGUI** [comment]
My output looks like this now:
![image](https://user-images.githubusercontent.com/46163555/86801658-44a10800-c042-11ea-90c2-d77cafd5ee7b.png)

**Comment by nngogol** [comment]
Fixed
