### ISSUE TITLE
Make an option to disable printing of events

### ISSUE THREAD

**Issue by PySimpleGUI** [nngogol/PySimpleGUIDocGen#65]
I don't get any value from seeing these constantly scrolling...

```
C:\Python\Anaconda3\python.exe "C:/Python/PycharmProjects/GooeyGUI/readme_creator/RUN_ME and START_HERE.py"
Такая папка уже есть: "C:\Python\PycharmProjects\GooeyGUI\readme_creator\output"
PSG event> -CALL_REF-listbox-
PSG event> F10:121
PSG event> -CALL_REF-listbox-
PSG event> F9:120
PSG event> Shift_L:16
PSG event> Control_L:17
PSG event> Escape:27
PSG event> MouseWheel:Up
PSG event> MouseWheel:Down
PSG event> MouseWheel:Down
PSG event> MouseWheel:Down
PSG event> MouseWheel:Down
PSG event> MouseWheel:Down
PSG event> MouseWheel:Down
PSG event> MouseWheel:Down
PSG event> MouseWheel:Down
PSG event> MouseWheel:Down
```

So I keep commenting out those lines of code when I get a release.  Otherwise I miss other important error messages just because I've moved my mouse.  I'm not sure why mouse events are needed at all.  Maybe they're being shown due to the enable keyboard events.  I tend to remove the `print(event, values)` calls when I make a real program that's released to other people.

Maybe another setting can be added to the General Settings page to control the low level debugging?

**Comment by nngogol** [comment]
Fixed
