### ISSUE TITLE
Where's the popup?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#9]
I just about had you trained!

I  lost my popup that keep asking for.   Do you understand why I keep asking for it?  It is to solve a problem.  When I double-click whatever the right .py file is, I see a FLASH of black square (my dos command) and then it disappears.  I have no clue if there was an error.  And no, I do not want to go digging around through a log file every time just to see if it finished without errors.

I tried adding a window onto the program, but dumps out as if it's exiting somewhere and not returning from the call to `cli()`

I don't understand why I'm having so much trouble following this code.

Here's the code I'm running at the bottom of your make_read_readme.py file
```python
if __name__ == '__main__':
	layout = [
				[sg.T('Make Real Readme!', font=('ANY 15'))],
				[sg.Output(size=(80,12))],
				[sg.OK()]]
	window = sg.Window('Make Real Readme', layout).Finalize()

	cli()
	print('Done creating the readme.')
	while True:
		event, values = window.Read()
		if event is None: break
	window.Close()
```

**Comment by nngogol** [comment]
if you look at [usage.py](https://github.com/nngogol/PySimpleGUIDocGen/blob/master/HOWDOI/usage.py), than you will find popup at EOF. Try to move `usage.py` to `db/`and run it.
